apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_HOST: ZWMyLTE4LTIwNi0xNjItMTIuY29tcHV0ZS0xLmFtYXpvbmF3cy5jb20K
  DB_PORT: NTQzMg==
  DB_USERNAME: b3Vzc2FtYQ==
  DB_PASSWORD: b3Vzc2FtYQ==
  DB_NAME: b3Vzc2FtYQ==
  DB_SYNCHRONIZE: dHJ1ZQ==


# === OR

# kubectl create secret generic db-secret \
#   --from-literal=DB_HOST=ec2-18-206-162-12.compute-1.amazonaws.com \
#   --from-literal=DB_PORT=5432 \
#   --from-literal=DB_USERNAME=oussama \
#   --from-literal=DB_PASSWORD=oussama \
#   --from-literal=DB_NAME=oussama \
#   --from-literal=DB_SYNCHRONIZE=true