apiVersion: v1
kind: Pod
metadata:
  name: my-app
  labels:
    app: my-app  # Add this label
spec:
  containers:
  - name: my-app-container
    image: workat00/your-nestjs-app:latest
    env:
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_HOST
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_PORT
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_USERNAME
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_PASSWORD
    - name: DB_NAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_NAME
    - name: DB_SYNCHRONIZE
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: DB_SYNCHRONIZE
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name