apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_HOST: cG9zdGdyZXMtc2VydmljZQo=   #postgres-service
  DB_PORT: NTQzMg==    #5432
  DB_USERNAME: b3Vzc2FtYQ==    #oussama
  DB_PASSWORD: b3Vzc2FtYQ==
  DB_NAME: b3Vzc2FtYQ==
  DB_SYNCHRONIZE: dHJ1ZQ==


# === OR

# kubectl create secret generic db-secret \
#   --from-literal=DB_HOST=postgres-service \
#   --from-literal=DB_PORT=5432 \
#   --from-literal=DB_USERNAME=oussama \
#   --from-literal=DB_PASSWORD=oussama \
#   --from-literal=DB_NAME=oussama \
#   --from-literal=DB_SYNCHRONIZE=true