apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  volumes:
  - name: postgres-data
    persistentVolumeClaim:
      claimName: postgres-pvc
  containers:
  - name: postgres-container
    image: postgres:latest
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: DB_USERNAME
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: DB_PASSWORD
    - name: POSTGRES_DB
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: DB_NAME
    - name: PGDATA
      value: "/var/lib/postgresql/data/pgdata"  # Use a subdirectory
    ports:
    - containerPort: 5432